site_name: APIrate docs

theme:
  name: "readthedocs"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: tutorials.md
  - Explanation: explanation.md